/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.awt.Frame;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.Socket;
import java.net.UnknownHostException;

import javax.swing.JOptionPane;

import connection.ConnectionSocket;

/**
 *
 * @author DungVan
 */
public class Register extends javax.swing.JFrame {

	/**
	 * Creates new form Login
	 */
	public Register() {
		initComponents();
		this.moveFrame.addMouseMotionListener(new MouseAdapter() {
			@Override
			public void mouseDragged(MouseEvent e) {
				super.mouseDragged(e);
				setLocation(e.getXOnScreen() - posX, e.getYOnScreen() - posY);
			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private void initComponents() {

		passField = new javax.swing.JPasswordField();
		passConfirm = new javax.swing.JPasswordField();
		tf_email = new javax.swing.JTextField();
		bt_submit = new javax.swing.JButton();
		bt_cancel = new javax.swing.JButton();
		moveFrame = new javax.swing.JLabel();
		close = new javax.swing.JLabel();
		minimize = new javax.swing.JLabel();
		background = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setFocusTraversalPolicyProvider(true);
		setUndecorated(true);
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		passField.setBackground(new java.awt.Color(202, 229, 202));
		passField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		passField.setBorder(null);
		passField.setOpaque(false);
		getContentPane().add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 150, 30));

		passConfirm.setBackground(new java.awt.Color(202, 229, 202));
		passConfirm.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		passConfirm.setBorder(null);
		passConfirm.setOpaque(false);
		getContentPane().add(passConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 150, 20));

		tf_email.setBackground(new java.awt.Color(202, 229, 202));
		tf_email.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		tf_email.setBorder(null);
		tf_email.setOpaque(false);
		getContentPane().add(tf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 150, 30));

		bt_submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/submit.png")));
		bt_submit.setBorder(null);
		bt_submit.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				bt_submitMouseClicked(evt);
			}
		});
		getContentPane().add(bt_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 110, 40));

		bt_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/cancel.png")));
		bt_cancel.setAutoscrolls(true);
		getContentPane().add(bt_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 110, 40));
		bt_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				bt_cancelMouseClicked(evt);
			}
		});

		moveFrame.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
		moveFrame.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				moveFrameMousePressed(evt);
			}
		});
		getContentPane().add(moveFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 30));

		close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		close.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				closeMouseClicked(evt);
			}
		});
		getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 30, 30));

		minimize.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				minimizeMouseClicked(evt);
			}
		});
		getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 30, 30));

		background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/mc_register.png"))); // NOI18N
		background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 500));

		getAccessibleContext().setAccessibleParent(this);

		pack();
		setLocationRelativeTo(null);
	}

	private void closeMouseClicked(java.awt.event.MouseEvent evt) {

		new Login().setVisible(true);
		this.dispose();
	}

	private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {

		this.setState(Frame.ICONIFIED);
	}

	private void moveFrameMousePressed(java.awt.event.MouseEvent evt) {

		posX = evt.getX();
		posY = evt.getY();
	}

	@SuppressWarnings("deprecation")
	private void bt_submitMouseClicked(java.awt.event.MouseEvent evt) {
		/*
		 * check validate for textfield here
		 */
		if (tf_email.getText().length() < 1) {
			JOptionPane.showMessageDialog(this, "Please provice your email!");
			return;
		}

		if (!passConfirm.getPassword().equals(passField.getPassword()) && passField.getPassword().length < 1) {
			JOptionPane.showMessageDialog(this, "Password dose not match!\nPlease try again!");
			return;
		}
		/*
		 * end check validate
		 */
		try {
			/*
			 * make connect to authentication server
			 */
			Socket socket = new Socket("localhost", 3001);
			ConnectionSocket conn = new ConnectionSocket(socket);
			/*
			 * send message create to request create new email
			 */
			conn.sendMsg("create");
			conn.sendMsg(this.tf_email.getText() + " " + this.passField.getText() + "\n");
			String line = conn.receive();
			
			if (line.equals("true")) {
				/*
				 * create successfully
				 */
				conn.closeConnection();
				JOptionPane.showMessageDialog(this, "email " + this.tf_email.getText() + " ready to use!");
				new Login().setVisible(true);
				this.dispose();
				return;
			} else if (line.equals("exist")) {
				/*
				 * email is exist
				 */
				conn.closeConnection();
				JOptionPane.showMessageDialog(this,
						"email " + this.tf_email.getText() + " is exist!\nPlease try another email!");
				tf_email.setText("");
				passField.setText("");
				passConfirm.setText("");
				return;
			} else {
				/*
				 * can not create new email
				 */
				conn.closeConnection();
				JOptionPane.showMessageDialog(this, "can't not create email right now!\nPlease try again later!");
				return;
			}
		} catch (UnknownHostException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void bt_cancelMouseClicked(java.awt.event.MouseEvent evt) {

		new Login().setVisible(true);
		this.dispose();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Register().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private int posX, posY;
	private javax.swing.JLabel background;
	private javax.swing.JButton bt_cancel;
	private javax.swing.JButton bt_submit;
	private javax.swing.JLabel close;
	private javax.swing.JLabel minimize;
	private javax.swing.JLabel moveFrame;
	private javax.swing.JPasswordField passConfirm;
	private javax.swing.JPasswordField passField;
	private javax.swing.JTextField tf_email;
	// End of variables declaration
}
