/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainserver;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import javax.swing.JLabel;

/**
 *
 * @author DungVan
 */
public class MainOption_GUI extends javax.swing.JFrame {

	/**
	 * Creates new form MainOption_GUI
	 */
	public MainOption_GUI() {
		initComponents();
		clientOption.add(custardServ);
		clientOption.add(bananaServ);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		clientOption = new javax.swing.ButtonGroup();
		submit = new javax.swing.JButton();
		custardServ = new javax.swing.JRadioButton();
		bananaServ = new javax.swing.JRadioButton();
		serverName = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);
		setType(java.awt.Window.Type.POPUP);
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		submit.setText("Done");
		submit.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				submitMouseClicked();
			}
		});
		getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

		custardServ.setText("custardapple.ddns.net");
		getContentPane().add(custardServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 20, 170, -1));

		bananaServ.setText("bananatieu.ddns.net");
		getContentPane().add(bananaServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 50, 170, -1));

		setSize(new java.awt.Dimension(228, 165));
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void submitMouseClicked() {
		// TODO add your handling code here:
		if (custardServ.isSelected()) {
			MainServer_GUI.SERVER_NAME = MainServer_GUI.SERVER_CUSTARDAPPLE;
		} else if (bananaServ.isSelected()) {
			MainServer_GUI.SERVER_NAME = MainServer_GUI.SERVER_BANANA;
		} else
			MainServer_GUI.SERVER_NAME = "localhost";
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainServer_GUI().setVisible(true);
			}
		});
		this.dispose();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {

		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainOption_GUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.ButtonGroup clientOption;
	private javax.swing.JRadioButton bananaServ;
	private javax.swing.JRadioButton custardServ;
	private javax.swing.JTextField serverName;
	private javax.swing.JButton submit;
	// End of variables declaration
}
