/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import javax.swing.JLabel;

import client.connetion.ConnectionServerOption;

/**
 *
 * @author DungVan
 */
public class MainOption_GUI extends javax.swing.JFrame {

	/**
	 * Creates new form MainOption_GUI
	 */
	public MainOption_GUI() {
		initComponents();
		clientOption.add(pop3Client);
		clientOption.add(imap4Client);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		setContentPane(new JLabel(new javax.swing.ImageIcon(getClass().getResource("/client/image/background.jpg"))));
		
		clientOption = new javax.swing.ButtonGroup();
		submit = new javax.swing.JButton();
		pop3Client = new javax.swing.JRadioButton();
		imap4Client = new javax.swing.JRadioButton();
		serverName = new javax.swing.JTextField();
		lb_serveraddress = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);
		setType(java.awt.Window.Type.POPUP);
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		submit.setText("Done");
		submit.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				submitMouseClicked();
			}
		});
		getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 99, -1, -1));

		pop3Client.setText("POP3 Client");
		getContentPane().add(pop3Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 16, -1, -1));

		imap4Client.setSelected(true);
		imap4Client.setText("IMAP4 Client");
		getContentPane().add(imap4Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));
		
		serverName.setBorder(null);
		serverName.addKeyListener(new KeyListener() {
			
			@Override
			public void keyTyped(KeyEvent arg0) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void keyReleased(KeyEvent arg0) {
				// TODO Auto-generated method stub
				if(arg0.getKeyCode() == KeyEvent.VK_ENTER){
					submitMouseClicked();
				}
			}
			
			@Override
			public void keyPressed(KeyEvent arg0) {
				// TODO Auto-generated method stub
				
			}
		});
		getContentPane().add(serverName, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 70, 170, -1));

		lb_serveraddress.setText("<html><p style = \"color : red\">Put Server address to connect</p></html>");
		getContentPane().add(lb_serveraddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 48, -1, -1));

		setSize(new java.awt.Dimension(228, 165));
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void submitMouseClicked() {
		// TODO add your handling code here:
		if (pop3Client.isSelected())
			Client_GUI.setCLIENT_TYPE("POP3");
		else
			Client_GUI.setCLIENT_TYPE("IMAP4");

		ConnectionServerOption.setSERVER_NAME(this.serverName.getText().trim());

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login_GUI().setVisible(true);
			}
		});
		this.dispose();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {

		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainOption_GUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.ButtonGroup clientOption;
	private javax.swing.JRadioButton imap4Client;
	private javax.swing.JLabel lb_serveraddress;
	private javax.swing.JRadioButton pop3Client;
	private javax.swing.JTextField serverName;
	private javax.swing.JButton submit;
	// End of variables declaration
}
