/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.gui;

import java.awt.Frame;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author DungVan
 */
public class Main_GUI extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private static String USER_EMAIL;
	
	public static String getUSER_EMAIL() {
		return USER_EMAIL;
	}

	public static void setUSER_EMAIL(String uSER_EMAIL) {
		USER_EMAIL = uSER_EMAIL;
	}

	/**
	 * Creates new form Main_GUI
	 */
	public Main_GUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		mailbody = new javax.swing.JTextArea();
		jScrollPane = new javax.swing.JScrollPane(mailbox);
		close = new javax.swing.JLabel();
		minimize = new javax.swing.JLabel();
		logout = new javax.swing.JLabel();
		createmail = new javax.swing.JLabel();
		mailbox = new javax.swing.JLabel();
		moveFrame = new javax.swing.JLabel();
		background = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setUndecorated(true);
		setOpacity(0.9F);
		setResizable(false);
		setSize(new java.awt.Dimension(300, 300));
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		mailbody.setText("");
		mailbody.setLineWrap(true);
		mailbody.setWrapStyleWord(true);
		mailbody.setBorder(null);
		mailbody.setEditable(false);
		mailbody.setBackground(new java.awt.Color(244, 241, 185));

		jScrollPane.setBorder(null);
		getContentPane().add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 180, 343, 320));

		close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		close.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				closeMouseClicked(evt);
			}
		});
		getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, 30));

		minimize.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent evt) {
				minimizeMouseClicked(evt);
			}
		});
		getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 30, 30));

		logout.setText("logout");
		logout.setForeground(new java.awt.Color(255, 255, 0));
		logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		logout.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				logoutMouseClicked(evt);
			}
		});
		getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, -1));

		createmail.setText("Create Mail");
		createmail.setForeground(new java.awt.Color(255, 255, 0));
		createmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		createmail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		createmail.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				createmailMouseClicked(evt);
			}
		});
		getContentPane().add(createmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, -1));

		mailbox.setForeground(new java.awt.Color(255, 255, 0));
		mailbox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		mailbox.setText("Mail Box");
		mailbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		getContentPane().add(mailbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, -1));

		moveFrame.setForeground(new java.awt.Color(204, 204, 0));
		moveFrame.setText("<html><b>  Main mail client</b></html>");
		moveFrame.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
		moveFrame.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				moveFrameMousePressed(evt);
			}
		});
		moveFrame.addMouseMotionListener(new MouseAdapter() {
			@Override
			public void mouseDragged(MouseEvent e) {
				super.mouseDragged(e); // To change body of generated methods,
										// choose Tools | Templates.
				setLocation(e.getXOnScreen() - posX, e.getYOnScreen() - posY);
			}
		});
		getContentPane().add(moveFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 435, 30));

		background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/image/mainGUI.png"))); // NOI18N
		background.setVerticalAlignment(javax.swing.SwingConstants.TOP);
		getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>

	protected void createmailMouseClicked(MouseEvent evt) {
		// TODO Auto-generated method stub
		Thread t = new Thread() {
			public void run() {
				new SendMail_GUI().setVisible(true);
			}
		};
		t.start();
	}

	protected void logoutMouseClicked(MouseEvent evt) {
		// TODO Auto-generated method stub
		new Login_GUI().setVisible(true);
		this.dispose();
	}

	private void closeMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {
		this.setState(Frame.ICONIFIED);
	}

	private void moveFrameMousePressed(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		posX = evt.getX();
		posY = evt.getY();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Main_GUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private int posX, posY;
	private javax.swing.JLabel background;
	private javax.swing.JLabel moveFrame;
	private javax.swing.JLabel mailbox;
	private javax.swing.JLabel createmail;
	private javax.swing.JLabel logout;
	private javax.swing.JLabel minimize;
	private javax.swing.JLabel close;
	private javax.swing.JTextArea mailbody;
	private javax.swing.JScrollPane jScrollPane;
	// End of variables declaration
}
